package box.db;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsitemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public GoodsitemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ename is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ename is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ename =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ename <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ename >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ename >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ename <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ename <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ename like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ename not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ename in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ename not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ename between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ename not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andPsIsNull() {
            addCriterion("ps is null");
            return (Criteria) this;
        }

        public Criteria andPsIsNotNull() {
            addCriterion("ps is not null");
            return (Criteria) this;
        }

        public Criteria andPsEqualTo(Integer value) {
            addCriterion("ps =", value, "ps");
            return (Criteria) this;
        }

        public Criteria andPsNotEqualTo(Integer value) {
            addCriterion("ps <>", value, "ps");
            return (Criteria) this;
        }

        public Criteria andPsGreaterThan(Integer value) {
            addCriterion("ps >", value, "ps");
            return (Criteria) this;
        }

        public Criteria andPsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ps >=", value, "ps");
            return (Criteria) this;
        }

        public Criteria andPsLessThan(Integer value) {
            addCriterion("ps <", value, "ps");
            return (Criteria) this;
        }

        public Criteria andPsLessThanOrEqualTo(Integer value) {
            addCriterion("ps <=", value, "ps");
            return (Criteria) this;
        }

        public Criteria andPsIn(List<Integer> values) {
            addCriterion("ps in", values, "ps");
            return (Criteria) this;
        }

        public Criteria andPsNotIn(List<Integer> values) {
            addCriterion("ps not in", values, "ps");
            return (Criteria) this;
        }

        public Criteria andPsBetween(Integer value1, Integer value2) {
            addCriterion("ps between", value1, value2, "ps");
            return (Criteria) this;
        }

        public Criteria andPsNotBetween(Integer value1, Integer value2) {
            addCriterion("ps not between", value1, value2, "ps");
            return (Criteria) this;
        }

        public Criteria andEpsIsNull() {
            addCriterion("eps is null");
            return (Criteria) this;
        }

        public Criteria andEpsIsNotNull() {
            addCriterion("eps is not null");
            return (Criteria) this;
        }

        public Criteria andEpsEqualTo(Integer value) {
            addCriterion("eps =", value, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsNotEqualTo(Integer value) {
            addCriterion("eps <>", value, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsGreaterThan(Integer value) {
            addCriterion("eps >", value, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsGreaterThanOrEqualTo(Integer value) {
            addCriterion("eps >=", value, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsLessThan(Integer value) {
            addCriterion("eps <", value, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsLessThanOrEqualTo(Integer value) {
            addCriterion("eps <=", value, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsIn(List<Integer> values) {
            addCriterion("eps in", values, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsNotIn(List<Integer> values) {
            addCriterion("eps not in", values, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsBetween(Integer value1, Integer value2) {
            addCriterion("eps between", value1, value2, "eps");
            return (Criteria) this;
        }

        public Criteria andEpsNotBetween(Integer value1, Integer value2) {
            addCriterion("eps not between", value1, value2, "eps");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(String value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(String value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(String value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(String value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(String value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(String value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLike(String value) {
            addCriterion("sid like", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotLike(String value) {
            addCriterion("sid not like", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<String> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<String> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(String value1, String value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(String value1, String value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSid2IsNull() {
            addCriterion("sid2 is null");
            return (Criteria) this;
        }

        public Criteria andSid2IsNotNull() {
            addCriterion("sid2 is not null");
            return (Criteria) this;
        }

        public Criteria andSid2EqualTo(String value) {
            addCriterion("sid2 =", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2NotEqualTo(String value) {
            addCriterion("sid2 <>", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2GreaterThan(String value) {
            addCriterion("sid2 >", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2GreaterThanOrEqualTo(String value) {
            addCriterion("sid2 >=", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2LessThan(String value) {
            addCriterion("sid2 <", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2LessThanOrEqualTo(String value) {
            addCriterion("sid2 <=", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2Like(String value) {
            addCriterion("sid2 like", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2NotLike(String value) {
            addCriterion("sid2 not like", value, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2In(List<String> values) {
            addCriterion("sid2 in", values, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2NotIn(List<String> values) {
            addCriterion("sid2 not in", values, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2Between(String value1, String value2) {
            addCriterion("sid2 between", value1, value2, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid2NotBetween(String value1, String value2) {
            addCriterion("sid2 not between", value1, value2, "sid2");
            return (Criteria) this;
        }

        public Criteria andSid3IsNull() {
            addCriterion("sid3 is null");
            return (Criteria) this;
        }

        public Criteria andSid3IsNotNull() {
            addCriterion("sid3 is not null");
            return (Criteria) this;
        }

        public Criteria andSid3EqualTo(String value) {
            addCriterion("sid3 =", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3NotEqualTo(String value) {
            addCriterion("sid3 <>", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3GreaterThan(String value) {
            addCriterion("sid3 >", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3GreaterThanOrEqualTo(String value) {
            addCriterion("sid3 >=", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3LessThan(String value) {
            addCriterion("sid3 <", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3LessThanOrEqualTo(String value) {
            addCriterion("sid3 <=", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3Like(String value) {
            addCriterion("sid3 like", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3NotLike(String value) {
            addCriterion("sid3 not like", value, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3In(List<String> values) {
            addCriterion("sid3 in", values, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3NotIn(List<String> values) {
            addCriterion("sid3 not in", values, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3Between(String value1, String value2) {
            addCriterion("sid3 between", value1, value2, "sid3");
            return (Criteria) this;
        }

        public Criteria andSid3NotBetween(String value1, String value2) {
            addCriterion("sid3 not between", value1, value2, "sid3");
            return (Criteria) this;
        }

        public Criteria andCdescIsNull() {
            addCriterion("cdesc is null");
            return (Criteria) this;
        }

        public Criteria andCdescIsNotNull() {
            addCriterion("cdesc is not null");
            return (Criteria) this;
        }

        public Criteria andCdescEqualTo(String value) {
            addCriterion("cdesc =", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescNotEqualTo(String value) {
            addCriterion("cdesc <>", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescGreaterThan(String value) {
            addCriterion("cdesc >", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescGreaterThanOrEqualTo(String value) {
            addCriterion("cdesc >=", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescLessThan(String value) {
            addCriterion("cdesc <", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescLessThanOrEqualTo(String value) {
            addCriterion("cdesc <=", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescLike(String value) {
            addCriterion("cdesc like", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescNotLike(String value) {
            addCriterion("cdesc not like", value, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescIn(List<String> values) {
            addCriterion("cdesc in", values, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescNotIn(List<String> values) {
            addCriterion("cdesc not in", values, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescBetween(String value1, String value2) {
            addCriterion("cdesc between", value1, value2, "cdesc");
            return (Criteria) this;
        }

        public Criteria andCdescNotBetween(String value1, String value2) {
            addCriterion("cdesc not between", value1, value2, "cdesc");
            return (Criteria) this;
        }

        public Criteria andEdescIsNull() {
            addCriterion("edesc is null");
            return (Criteria) this;
        }

        public Criteria andEdescIsNotNull() {
            addCriterion("edesc is not null");
            return (Criteria) this;
        }

        public Criteria andEdescEqualTo(String value) {
            addCriterion("edesc =", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescNotEqualTo(String value) {
            addCriterion("edesc <>", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescGreaterThan(String value) {
            addCriterion("edesc >", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescGreaterThanOrEqualTo(String value) {
            addCriterion("edesc >=", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescLessThan(String value) {
            addCriterion("edesc <", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescLessThanOrEqualTo(String value) {
            addCriterion("edesc <=", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescLike(String value) {
            addCriterion("edesc like", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescNotLike(String value) {
            addCriterion("edesc not like", value, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescIn(List<String> values) {
            addCriterion("edesc in", values, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescNotIn(List<String> values) {
            addCriterion("edesc not in", values, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescBetween(String value1, String value2) {
            addCriterion("edesc between", value1, value2, "edesc");
            return (Criteria) this;
        }

        public Criteria andEdescNotBetween(String value1, String value2) {
            addCriterion("edesc not between", value1, value2, "edesc");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCrdateIsNull() {
            addCriterion("crdate is null");
            return (Criteria) this;
        }

        public Criteria andCrdateIsNotNull() {
            addCriterion("crdate is not null");
            return (Criteria) this;
        }

        public Criteria andCrdateEqualTo(Date value) {
            addCriterion("crdate =", value, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateNotEqualTo(Date value) {
            addCriterion("crdate <>", value, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateGreaterThan(Date value) {
            addCriterion("crdate >", value, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateGreaterThanOrEqualTo(Date value) {
            addCriterion("crdate >=", value, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateLessThan(Date value) {
            addCriterion("crdate <", value, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateLessThanOrEqualTo(Date value) {
            addCriterion("crdate <=", value, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateIn(List<Date> values) {
            addCriterion("crdate in", values, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateNotIn(List<Date> values) {
            addCriterion("crdate not in", values, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateBetween(Date value1, Date value2) {
            addCriterion("crdate between", value1, value2, "crdate");
            return (Criteria) this;
        }

        public Criteria andCrdateNotBetween(Date value1, Date value2) {
            addCriterion("crdate not between", value1, value2, "crdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goodsitem
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 23 16:11:40 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}