package box.db;

import java.util.Date;

public class Siteurl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column siteurl.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column siteurl.site
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column siteurl.caturl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String caturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column siteurl.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column siteurl.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column siteurl.id
     *
     * @return the value of siteurl.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column siteurl.id
     *
     * @param id the value for siteurl.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column siteurl.site
     *
     * @return the value of siteurl.site
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column siteurl.site
     *
     * @param site the value for siteurl.site
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column siteurl.caturl
     *
     * @return the value of siteurl.caturl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getCaturl() {
        return caturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column siteurl.caturl
     *
     * @param caturl the value for siteurl.caturl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setCaturl(String caturl) {
        this.caturl = caturl == null ? null : caturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column siteurl.status
     *
     * @return the value of siteurl.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column siteurl.status
     *
     * @param status the value for siteurl.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column siteurl.crdate
     *
     * @return the value of siteurl.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column siteurl.crdate
     *
     * @param crdate the value for siteurl.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}