package box.db;

import java.util.Date;

public class Wxpublic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.id
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.wxname
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private String wxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.wxhao
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private String wxhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.opendi
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private String opendi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.type
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.status
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxpublic.crdate
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.id
     *
     * @return the value of wxpublic.id
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.id
     *
     * @param id the value for wxpublic.id
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.wxname
     *
     * @return the value of wxpublic.wxname
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public String getWxname() {
        return wxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.wxname
     *
     * @param wxname the value for wxpublic.wxname
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setWxname(String wxname) {
        this.wxname = wxname == null ? null : wxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.wxhao
     *
     * @return the value of wxpublic.wxhao
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public String getWxhao() {
        return wxhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.wxhao
     *
     * @param wxhao the value for wxpublic.wxhao
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setWxhao(String wxhao) {
        this.wxhao = wxhao == null ? null : wxhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.opendi
     *
     * @return the value of wxpublic.opendi
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public String getOpendi() {
        return opendi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.opendi
     *
     * @param opendi the value for wxpublic.opendi
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setOpendi(String opendi) {
        this.opendi = opendi == null ? null : opendi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.type
     *
     * @return the value of wxpublic.type
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.type
     *
     * @param type the value for wxpublic.type
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.status
     *
     * @return the value of wxpublic.status
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.status
     *
     * @param status the value for wxpublic.status
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxpublic.crdate
     *
     * @return the value of wxpublic.crdate
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxpublic.crdate
     *
     * @param crdate the value for wxpublic.crdate
     *
     * @mbggenerated Fri Mar 27 10:01:03 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}