package box.db;

import box.db.Wxsite;
import box.db.WxsiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxsiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int countByExample(WxsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int deleteByExample(WxsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int insert(Wxsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int insertSelective(Wxsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    List<Wxsite> selectByExample(WxsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    Wxsite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") Wxsite record, @Param("example") WxsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int updateByExample(@Param("record") Wxsite record, @Param("example") WxsiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int updateByPrimaryKeySelective(Wxsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxsite
     *
     * @mbggenerated Fri Mar 27 21:06:31 CST 2015
     */
    int updateByPrimaryKey(Wxsite record);
}