package box.db;

import java.util.Date;

public class Wxtitle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.id
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.wxhao
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private String wxhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.wxname
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private String wxname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.openid
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.title
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.titleurl
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private String titleurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.titlekey
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private String titlekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.viewcount
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private Integer viewcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.zancount
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private Integer zancount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.status
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.crdate
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private Date crdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtitle.udate
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    private Date udate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.id
     *
     * @return the value of wxtitle.id
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.id
     *
     * @param id the value for wxtitle.id
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.wxhao
     *
     * @return the value of wxtitle.wxhao
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public String getWxhao() {
        return wxhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.wxhao
     *
     * @param wxhao the value for wxtitle.wxhao
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setWxhao(String wxhao) {
        this.wxhao = wxhao == null ? null : wxhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.wxname
     *
     * @return the value of wxtitle.wxname
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public String getWxname() {
        return wxname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.wxname
     *
     * @param wxname the value for wxtitle.wxname
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setWxname(String wxname) {
        this.wxname = wxname == null ? null : wxname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.openid
     *
     * @return the value of wxtitle.openid
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.openid
     *
     * @param openid the value for wxtitle.openid
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.title
     *
     * @return the value of wxtitle.title
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.title
     *
     * @param title the value for wxtitle.title
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.titleurl
     *
     * @return the value of wxtitle.titleurl
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public String getTitleurl() {
        return titleurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.titleurl
     *
     * @param titleurl the value for wxtitle.titleurl
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setTitleurl(String titleurl) {
        this.titleurl = titleurl == null ? null : titleurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.titlekey
     *
     * @return the value of wxtitle.titlekey
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public String getTitlekey() {
        return titlekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.titlekey
     *
     * @param titlekey the value for wxtitle.titlekey
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setTitlekey(String titlekey) {
        this.titlekey = titlekey == null ? null : titlekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.viewcount
     *
     * @return the value of wxtitle.viewcount
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public Integer getViewcount() {
        return viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.viewcount
     *
     * @param viewcount the value for wxtitle.viewcount
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setViewcount(Integer viewcount) {
        this.viewcount = viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.zancount
     *
     * @return the value of wxtitle.zancount
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public Integer getZancount() {
        return zancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.zancount
     *
     * @param zancount the value for wxtitle.zancount
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setZancount(Integer zancount) {
        this.zancount = zancount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.status
     *
     * @return the value of wxtitle.status
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.status
     *
     * @param status the value for wxtitle.status
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.crdate
     *
     * @return the value of wxtitle.crdate
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.crdate
     *
     * @param crdate the value for wxtitle.crdate
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtitle.udate
     *
     * @return the value of wxtitle.udate
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public Date getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtitle.udate
     *
     * @param udate the value for wxtitle.udate
     *
     * @mbggenerated Fri Mar 27 18:38:37 CST 2015
     */
    public void setUdate(Date udate) {
        this.udate = udate;
    }
}