package box.site.model;

import java.util.Date;

public class Baiduurls {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baiduurls.autoid
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    private Integer autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baiduurls.url
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baiduurls.wordid
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    private Integer wordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baiduurls.word
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baiduurls.status
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column baiduurls.crdate
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baiduurls.autoid
     *
     * @return the value of baiduurls.autoid
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public Integer getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baiduurls.autoid
     *
     * @param autoid the value for baiduurls.autoid
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public void setAutoid(Integer autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baiduurls.url
     *
     * @return the value of baiduurls.url
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baiduurls.url
     *
     * @param url the value for baiduurls.url
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baiduurls.wordid
     *
     * @return the value of baiduurls.wordid
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public Integer getWordid() {
        return wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baiduurls.wordid
     *
     * @param wordid the value for baiduurls.wordid
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public void setWordid(Integer wordid) {
        this.wordid = wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baiduurls.word
     *
     * @return the value of baiduurls.word
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baiduurls.word
     *
     * @param word the value for baiduurls.word
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baiduurls.status
     *
     * @return the value of baiduurls.status
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baiduurls.status
     *
     * @param status the value for baiduurls.status
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baiduurls.crdate
     *
     * @return the value of baiduurls.crdate
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baiduurls.crdate
     *
     * @param crdate the value for baiduurls.crdate
     *
     * @mbggenerated Fri Apr 01 17:34:16 CST 2016
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}