package box.site.model;

import box.site.model.Searchurl;
import box.site.model.SearchurlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SearchurlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int countByExample(SearchurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int deleteByExample(SearchurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int insert(Searchurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int insertSelective(Searchurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    List<Searchurl> selectByExample(SearchurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    Searchurl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int updateByExampleSelective(@Param("record") Searchurl record, @Param("example") SearchurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int updateByExample(@Param("record") Searchurl record, @Param("example") SearchurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int updateByPrimaryKeySelective(Searchurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table searchurl
     *
     * @mbggenerated Wed Dec 30 17:57:15 CST 2015
     */
    int updateByPrimaryKey(Searchurl record);
}