package box.site.model;

import java.util.Date;

public class Shoppingdata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.id
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.ctitle
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private String ctitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.typeid
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.urlstr
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private String urlstr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.fromsite
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private String fromsite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.imgurl
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shoppingdata.crdate
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.id
     *
     * @return the value of shoppingdata.id
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.id
     *
     * @param id the value for shoppingdata.id
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.ctitle
     *
     * @return the value of shoppingdata.ctitle
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public String getCtitle() {
        return ctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.ctitle
     *
     * @param ctitle the value for shoppingdata.ctitle
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setCtitle(String ctitle) {
        this.ctitle = ctitle == null ? null : ctitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.typeid
     *
     * @return the value of shoppingdata.typeid
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.typeid
     *
     * @param typeid the value for shoppingdata.typeid
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.urlstr
     *
     * @return the value of shoppingdata.urlstr
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public String getUrlstr() {
        return urlstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.urlstr
     *
     * @param urlstr the value for shoppingdata.urlstr
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setUrlstr(String urlstr) {
        this.urlstr = urlstr == null ? null : urlstr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.fromsite
     *
     * @return the value of shoppingdata.fromsite
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public String getFromsite() {
        return fromsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.fromsite
     *
     * @param fromsite the value for shoppingdata.fromsite
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setFromsite(String fromsite) {
        this.fromsite = fromsite == null ? null : fromsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.imgurl
     *
     * @return the value of shoppingdata.imgurl
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.imgurl
     *
     * @param imgurl the value for shoppingdata.imgurl
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shoppingdata.crdate
     *
     * @return the value of shoppingdata.crdate
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shoppingdata.crdate
     *
     * @param crdate the value for shoppingdata.crdate
     *
     * @mbggenerated Fri May 20 09:15:27 CST 2016
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}