package box.site.model;

import box.site.model.Websitewords;
import box.site.model.WebsitewordsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsitewordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int countByExample(WebsitewordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int deleteByExample(WebsitewordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int deleteByPrimaryKey(Integer autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int insert(Websitewords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int insertSelective(Websitewords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    List<Websitewords> selectByExample(WebsitewordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    Websitewords selectByPrimaryKey(Integer autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") Websitewords record, @Param("example") WebsitewordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int updateByExample(@Param("record") Websitewords record, @Param("example") WebsitewordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int updateByPrimaryKeySelective(Websitewords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitewords
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    int updateByPrimaryKey(Websitewords record);
}