package box.site.model;

import box.site.model.Websiteterms;
import box.site.model.WebsitetermsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsitetermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int countByExample(WebsitetermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int deleteByExample(WebsitetermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int insert(Websiteterms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int insertSelective(Websiteterms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    List<Websiteterms> selectByExample(WebsitetermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    Websiteterms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int updateByExampleSelective(@Param("record") Websiteterms record, @Param("example") WebsitetermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int updateByExample(@Param("record") Websiteterms record, @Param("example") WebsitetermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int updateByPrimaryKeySelective(Websiteterms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websiteterms
     *
     * @mbggenerated Wed Jun 01 11:55:25 CST 2016
     */
    int updateByPrimaryKey(Websiteterms record);
}