package box.site.model;

public class Websitekeys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.id
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.keyword
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.siteid
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.cat
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer cat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.id
     *
     * @return the value of websitekeys.id
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.id
     *
     * @param id the value for websitekeys.id
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.keyword
     *
     * @return the value of websitekeys.keyword
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.keyword
     *
     * @param keyword the value for websitekeys.keyword
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.siteid
     *
     * @return the value of websitekeys.siteid
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.siteid
     *
     * @param siteid the value for websitekeys.siteid
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.cat
     *
     * @return the value of websitekeys.cat
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.cat
     *
     * @param cat the value for websitekeys.cat
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setCat(Integer cat) {
        this.cat = cat;
    }
}