package box.site.model;

public class Websitekeys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.id
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.wordid
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    private Integer wordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitekeys.siteid
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    private Integer siteid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.id
     *
     * @return the value of websitekeys.id
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.id
     *
     * @param id the value for websitekeys.id
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.wordid
     *
     * @return the value of websitekeys.wordid
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    public Integer getWordid() {
        return wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.wordid
     *
     * @param wordid the value for websitekeys.wordid
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    public void setWordid(Integer wordid) {
        this.wordid = wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitekeys.siteid
     *
     * @return the value of websitekeys.siteid
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitekeys.siteid
     *
     * @param siteid the value for websitekeys.siteid
     *
     * @mbggenerated Fri Apr 01 15:26:04 CST 2016
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }
}