package box.site.model;

import java.util.Date;

public class Website {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.siteid
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private Integer siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.name
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.url
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.baiduurl
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private String baiduurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.cdesc
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private String cdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.bdrank
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private Integer bdrank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.alexa
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private Integer alexa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.googlerank
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private Integer googlerank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.remark
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.crdate
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private Date crdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.status
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.siteid
     *
     * @return the value of website.siteid
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.siteid
     *
     * @param siteid the value for website.siteid
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.name
     *
     * @return the value of website.name
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.name
     *
     * @param name the value for website.name
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.url
     *
     * @return the value of website.url
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.url
     *
     * @param url the value for website.url
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.baiduurl
     *
     * @return the value of website.baiduurl
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public String getBaiduurl() {
        return baiduurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.baiduurl
     *
     * @param baiduurl the value for website.baiduurl
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setBaiduurl(String baiduurl) {
        this.baiduurl = baiduurl == null ? null : baiduurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.cdesc
     *
     * @return the value of website.cdesc
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.cdesc
     *
     * @param cdesc the value for website.cdesc
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc == null ? null : cdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.bdrank
     *
     * @return the value of website.bdrank
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public Integer getBdrank() {
        return bdrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.bdrank
     *
     * @param bdrank the value for website.bdrank
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setBdrank(Integer bdrank) {
        this.bdrank = bdrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.alexa
     *
     * @return the value of website.alexa
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public Integer getAlexa() {
        return alexa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.alexa
     *
     * @param alexa the value for website.alexa
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setAlexa(Integer alexa) {
        this.alexa = alexa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.googlerank
     *
     * @return the value of website.googlerank
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public Integer getGooglerank() {
        return googlerank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.googlerank
     *
     * @param googlerank the value for website.googlerank
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setGooglerank(Integer googlerank) {
        this.googlerank = googlerank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.remark
     *
     * @return the value of website.remark
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.remark
     *
     * @param remark the value for website.remark
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.crdate
     *
     * @return the value of website.crdate
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.crdate
     *
     * @param crdate the value for website.crdate
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.status
     *
     * @return the value of website.status
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.status
     *
     * @param status the value for website.status
     *
     * @mbggenerated Fri Apr 01 16:38:18 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}