package box.site.model;

import java.util.Date;

public class Websitewords implements Comparable{
	

    @Override
    public int compareTo(Object o)
    {

    	Websitewords sdto = (Websitewords)o;

    	Integer otherMoney = sdto.getSitecount();

          return otherMoney.compareTo(this.getSitecount());
    }
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.autoid
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private Integer autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.wordid
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private Integer wordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.word
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.cat
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private Integer cat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.sitecount
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private Integer sitecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.status
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column websitewords.crdate
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.autoid
     *
     * @return the value of websitewords.autoid
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public Integer getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.autoid
     *
     * @param autoid the value for websitewords.autoid
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setAutoid(Integer autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.wordid
     *
     * @return the value of websitewords.wordid
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public Integer getWordid() {
        return wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.wordid
     *
     * @param wordid the value for websitewords.wordid
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setWordid(Integer wordid) {
        this.wordid = wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.word
     *
     * @return the value of websitewords.word
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.word
     *
     * @param word the value for websitewords.word
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.cat
     *
     * @return the value of websitewords.cat
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public Integer getCat() {
        return cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.cat
     *
     * @param cat the value for websitewords.cat
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setCat(Integer cat) {
        this.cat = cat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.sitecount
     *
     * @return the value of websitewords.sitecount
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public Integer getSitecount() {
        return sitecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.sitecount
     *
     * @param sitecount the value for websitewords.sitecount
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setSitecount(Integer sitecount) {
        this.sitecount = sitecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.status
     *
     * @return the value of websitewords.status
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.status
     *
     * @param status the value for websitewords.status
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column websitewords.crdate
     *
     * @return the value of websitewords.crdate
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column websitewords.crdate
     *
     * @param crdate the value for websitewords.crdate
     *
     * @mbggenerated Sat May 14 09:02:30 CST 2016
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}