package box.site.model;

import box.site.model.Websitekeys;
import box.site.model.WebsitekeysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsitekeysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int countByExample(WebsitekeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int deleteByExample(WebsitekeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int insert(Websitekeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int insertSelective(Websitekeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    List<Websitekeys> selectByExample(WebsitekeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    Websitekeys selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int updateByExampleSelective(@Param("record") Websitekeys record, @Param("example") WebsitekeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int updateByExample(@Param("record") Websitekeys record, @Param("example") WebsitekeysExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int updateByPrimaryKeySelective(Websitekeys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websitekeys
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    int updateByPrimaryKey(Websitekeys record);
}