package box.site.model;

import java.util.Date;

public class Website {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.siteid
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer siteid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.name
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.url
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.desc
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.bdrank
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer bdrank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.alexa
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer alexa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.googlerank
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Integer googlerank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.remark
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column website.crdate
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.siteid
     *
     * @return the value of website.siteid
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getSiteid() {
        return siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.siteid
     *
     * @param siteid the value for website.siteid
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setSiteid(Integer siteid) {
        this.siteid = siteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.name
     *
     * @return the value of website.name
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.name
     *
     * @param name the value for website.name
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.url
     *
     * @return the value of website.url
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.url
     *
     * @param url the value for website.url
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.desc
     *
     * @return the value of website.desc
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.desc
     *
     * @param desc the value for website.desc
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.bdrank
     *
     * @return the value of website.bdrank
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getBdrank() {
        return bdrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.bdrank
     *
     * @param bdrank the value for website.bdrank
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setBdrank(Integer bdrank) {
        this.bdrank = bdrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.alexa
     *
     * @return the value of website.alexa
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getAlexa() {
        return alexa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.alexa
     *
     * @param alexa the value for website.alexa
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setAlexa(Integer alexa) {
        this.alexa = alexa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.googlerank
     *
     * @return the value of website.googlerank
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Integer getGooglerank() {
        return googlerank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.googlerank
     *
     * @param googlerank the value for website.googlerank
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setGooglerank(Integer googlerank) {
        this.googlerank = googlerank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.remark
     *
     * @return the value of website.remark
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.remark
     *
     * @param remark the value for website.remark
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column website.crdate
     *
     * @return the value of website.crdate
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column website.crdate
     *
     * @param crdate the value for website.crdate
     *
     * @mbggenerated Thu Dec 24 10:02:08 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}