package box.site.model;

import box.site.model.Wordrelation;
import box.site.model.WordrelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordrelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int countByExample(WordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int deleteByExample(WordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int deleteByPrimaryKey(Integer autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int insert(Wordrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int insertSelective(Wordrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    List<Wordrelation> selectByExample(WordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    Wordrelation selectByPrimaryKey(Integer autoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") Wordrelation record, @Param("example") WordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int updateByExample(@Param("record") Wordrelation record, @Param("example") WordrelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int updateByPrimaryKeySelective(Wordrelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordrelation
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    int updateByPrimaryKey(Wordrelation record);
}