package box.site.model;

public class Wordrelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wordrelation.autoid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    private Integer autoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wordrelation.wordid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    private Integer wordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wordrelation.relatewordid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    private Integer relatewordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wordrelation.relatetype
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    private Integer relatetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wordrelation.autoid
     *
     * @return the value of wordrelation.autoid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public Integer getAutoid() {
        return autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wordrelation.autoid
     *
     * @param autoid the value for wordrelation.autoid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public void setAutoid(Integer autoid) {
        this.autoid = autoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wordrelation.wordid
     *
     * @return the value of wordrelation.wordid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public Integer getWordid() {
        return wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wordrelation.wordid
     *
     * @param wordid the value for wordrelation.wordid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public void setWordid(Integer wordid) {
        this.wordid = wordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wordrelation.relatewordid
     *
     * @return the value of wordrelation.relatewordid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public Integer getRelatewordid() {
        return relatewordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wordrelation.relatewordid
     *
     * @param relatewordid the value for wordrelation.relatewordid
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public void setRelatewordid(Integer relatewordid) {
        this.relatewordid = relatewordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wordrelation.relatetype
     *
     * @return the value of wordrelation.relatetype
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public Integer getRelatetype() {
        return relatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wordrelation.relatetype
     *
     * @param relatetype the value for wordrelation.relatetype
     *
     * @mbggenerated Fri Apr 15 13:54:12 CST 2016
     */
    public void setRelatetype(Integer relatetype) {
        this.relatetype = relatetype;
    }
}