package box.db;

import java.util.Date;

public class Goodsitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.name
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.ename
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.ps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer ps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.eps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer eps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.sid
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.sid2
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String sid2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.sid3
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String sid3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.cdesc
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String cdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.edesc
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String edesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsitem.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.id
     *
     * @return the value of goodsitem.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.id
     *
     * @param id the value for goodsitem.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.name
     *
     * @return the value of goodsitem.name
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.name
     *
     * @param name the value for goodsitem.name
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.ename
     *
     * @return the value of goodsitem.ename
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.ename
     *
     * @param ename the value for goodsitem.ename
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.ps
     *
     * @return the value of goodsitem.ps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getPs() {
        return ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.ps
     *
     * @param ps the value for goodsitem.ps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setPs(Integer ps) {
        this.ps = ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.eps
     *
     * @return the value of goodsitem.eps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getEps() {
        return eps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.eps
     *
     * @param eps the value for goodsitem.eps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setEps(Integer eps) {
        this.eps = eps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.sid
     *
     * @return the value of goodsitem.sid
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.sid
     *
     * @param sid the value for goodsitem.sid
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.sid2
     *
     * @return the value of goodsitem.sid2
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getSid2() {
        return sid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.sid2
     *
     * @param sid2 the value for goodsitem.sid2
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setSid2(String sid2) {
        this.sid2 = sid2 == null ? null : sid2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.sid3
     *
     * @return the value of goodsitem.sid3
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getSid3() {
        return sid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.sid3
     *
     * @param sid3 the value for goodsitem.sid3
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setSid3(String sid3) {
        this.sid3 = sid3 == null ? null : sid3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.cdesc
     *
     * @return the value of goodsitem.cdesc
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getCdesc() {
        return cdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.cdesc
     *
     * @param cdesc the value for goodsitem.cdesc
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setCdesc(String cdesc) {
        this.cdesc = cdesc == null ? null : cdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.edesc
     *
     * @return the value of goodsitem.edesc
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getEdesc() {
        return edesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.edesc
     *
     * @param edesc the value for goodsitem.edesc
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setEdesc(String edesc) {
        this.edesc = edesc == null ? null : edesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.status
     *
     * @return the value of goodsitem.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.status
     *
     * @param status the value for goodsitem.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsitem.crdate
     *
     * @return the value of goodsitem.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsitem.crdate
     *
     * @param crdate the value for goodsitem.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}