package box.db;

import box.db.Goodsitem;
import box.db.GoodsitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int countByExample(GoodsitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int deleteByExample(GoodsitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int insert(Goodsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int insertSelective(Goodsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    List<Goodsitem> selectByExample(GoodsitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    Goodsitem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") Goodsitem record, @Param("example") GoodsitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByExample(@Param("record") Goodsitem record, @Param("example") GoodsitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByPrimaryKeySelective(Goodsitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsitem
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByPrimaryKey(Goodsitem record);
}