package box.db;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GoodsurlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int countByExample(GoodsurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int deleteByExample(GoodsurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int insert(Goodsurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int insertSelective(Goodsurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    List<Goodsurl> selectByExample(GoodsurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    Goodsurl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") Goodsurl record, @Param("example") GoodsurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByExample(@Param("record") Goodsurl record, @Param("example") GoodsurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByPrimaryKeySelective(Goodsurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByPrimaryKey(Goodsurl record);
}