package box.db;

import java.util.Date;

public class Goodsurl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.site
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String goodsurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.goodstype
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer goodstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.name
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.qty
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.sid
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.ps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer ps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.newps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer newps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.imgurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsurl.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    private Date crdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.id
     *
     * @return the value of goodsurl.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.id
     *
     * @param id the value for goodsurl.id
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.site
     *
     * @return the value of goodsurl.site
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.site
     *
     * @param site the value for goodsurl.site
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.goodsurl
     *
     * @return the value of goodsurl.goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getGoodsurl() {
        return goodsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.goodsurl
     *
     * @param goodsurl the value for goodsurl.goodsurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setGoodsurl(String goodsurl) {
        this.goodsurl = goodsurl == null ? null : goodsurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.goodstype
     *
     * @return the value of goodsurl.goodstype
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getGoodstype() {
        return goodstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.goodstype
     *
     * @param goodstype the value for goodsurl.goodstype
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setGoodstype(Integer goodstype) {
        this.goodstype = goodstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.name
     *
     * @return the value of goodsurl.name
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.name
     *
     * @param name the value for goodsurl.name
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.qty
     *
     * @return the value of goodsurl.qty
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.qty
     *
     * @param qty the value for goodsurl.qty
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.sid
     *
     * @return the value of goodsurl.sid
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.sid
     *
     * @param sid the value for goodsurl.sid
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.ps
     *
     * @return the value of goodsurl.ps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getPs() {
        return ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.ps
     *
     * @param ps the value for goodsurl.ps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setPs(Integer ps) {
        this.ps = ps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.newps
     *
     * @return the value of goodsurl.newps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getNewps() {
        return newps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.newps
     *
     * @param newps the value for goodsurl.newps
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setNewps(Integer newps) {
        this.newps = newps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.imgurl
     *
     * @return the value of goodsurl.imgurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.imgurl
     *
     * @param imgurl the value for goodsurl.imgurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.status
     *
     * @return the value of goodsurl.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.status
     *
     * @param status the value for goodsurl.status
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsurl.crdate
     *
     * @return the value of goodsurl.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public Date getCrdate() {
        return crdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsurl.crdate
     *
     * @param crdate the value for goodsurl.crdate
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    public void setCrdate(Date crdate) {
        this.crdate = crdate;
    }
}