package box.db;

import box.db.Siteurl;
import box.db.SiteurlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SiteurlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int countByExample(SiteurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int deleteByExample(SiteurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int insert(Siteurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int insertSelective(Siteurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    List<Siteurl> selectByExample(SiteurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    Siteurl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") Siteurl record, @Param("example") SiteurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByExample(@Param("record") Siteurl record, @Param("example") SiteurlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByPrimaryKeySelective(Siteurl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table siteurl
     *
     * @mbggenerated Mon Mar 23 16:11:40 CST 2015
     */
    int updateByPrimaryKey(Siteurl record);
}