package box.db;

public class Wxtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtype.id
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtype.name
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtype.type
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxtype.status
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtype.id
     *
     * @return the value of wxtype.id
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtype.id
     *
     * @param id the value for wxtype.id
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtype.name
     *
     * @return the value of wxtype.name
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtype.name
     *
     * @param name the value for wxtype.name
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtype.type
     *
     * @return the value of wxtype.type
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtype.type
     *
     * @param type the value for wxtype.type
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxtype.status
     *
     * @return the value of wxtype.status
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxtype.status
     *
     * @param status the value for wxtype.status
     *
     * @mbggenerated Sat Mar 28 14:57:52 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}